### ISSUE TITLE
[Example] Python - Adding an image text overlay builder

### ISSUE THREAD

**Issue by codingis4noobs2** [cloudinary-community/cloudinary-examples#118]
@colbyfayock 
While Cloudinary offers a Text Layer effect(Add a text layer on user defined co-ordinates), but I don't see any examples of it
I would like to add an example of the same

Here is a reference app I created using Streamlit & Cloudinary SDK: https://codingis4noobs2-expresso-main-9ocucm.streamlit.app/

Looking forward to your feedback!

**Comment by codingis4noobs2** [comment]
@colbyfayock can you have a look into this

**Comment by colbyfayock** [comment]
Check this out https://cloudinary.com/documentation/layers#text_layer_options

**Comment by colbyfayock** [comment]
Feel free to open a PR! The app should be its own project folder with all the code inside. Including a readme with instructions for how to set it up
