### ISSUE TITLE
[Example] Angular - Upload Widget

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#44]
Create a new example showing how to set up the Cloudinary Upload Widget in an Angular project.

See other frameworks for examples:

* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/nextjs-upload-widget-signed
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/solid-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/sveltekit-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/vue-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/remix-upload-widget-preset

**Comment by daniloff200** [comment]
Hi, @colbyfayock , I have one question.
Why do we need this for angular, if, as I see, there's an example of Angular video & image uploader. It is the same, isn't it

**Comment by colbyfayock** [comment]
hey @daniloff200 which angular example are you referring to? if im not mistaken, there's not one here anywhere 🤔 

you're welcome to pick it up though, but would love to see you elaborate

**Comment by daniloff200** [comment]
@colbyfayock  I mean [this one](https://cloudinary.com/documentation/angular_image_and_video_upload)

**Comment by colbyfayock** [comment]
ah got it - looking for examples specifically in this repository using the latest version and best practices of Angular itself

that example can certainly help you get started. i'd check out some of the other examples like the React example:

https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/react-upload-widget-preset/src/components/UploadWidget/UploadWidget.js

which attempt to also solve some loading considerations for better UX such as the `requestIdleCallback`, though i'm not familiar with Angular so not sure what can apply

**Comment by daniloff200** [comment]
@colbyfayock Okay, I understood :)
Gonna pick that one, I'm working with angular most of the time, and will be happy to help with this
Perhaps, some additional examples are needed for Angular?

**Comment by colbyfayock** [comment]
yes for sure! ill try to file some more issues for other examples, but if you have any experience of interesting problems that may be helpful, such as looking at other examples that exist in React or other frameworks, i'm open to ideas

for instance, are you able to create serverless functions in angular yet? work with forms and such? uploading is always a great topic and the Widget is just one example

**Comment by colbyfayock** [comment]
@daniloff200 are you still working on this?

**Comment by daniloff200** [comment]
hey!
Yeah, I'm  on it right now :) @colbyfayock

**Comment by daniloff200** [comment]
Well, it feels, I will unassign this one from myself
I've tried a different ways, how I can integrate (according to the way, used in sandbox above), but, still have this issue -> 
![Selection_004](https://github.com/cloudinary-community/cloudinary-examples/assets/13692220/88265909-a0f5-43a2-88a8-84ca6a5e2914)

I also tried to use SDK, which mentioned [here](https://cloudinary.com/documentation/angular_quick_start), but, SDK does not provide any methods for  upload widget

I've also tried to get the code from widget url - https://upload-widget.cloudinary.com/2.10.1/global/all.js - here, and use it somehow it the project, but, it also was not helpful

Gonna ask some of my dev-folks tomorrow, maybe they have idea, how I can do that, if not, sorry, I've tried :(

**Comment by colbyfayock** [comment]
@daniloff200 that might simply be a lack of TS definitions. Try adding an @ts-ignore and see if it works without the type check

**Comment by daniloff200** [comment]
Well, that's strange, but it worked :D  @colbyfayock 
I didn't expect that could help, but, it is .

Gonna create a PR today then

**Comment by colbyfayock** [comment]
Awesome! I'll review soon
