### ISSUE TITLE
[Example] Nuxt - Upload Widget

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#45]
Create a new example showing how to set up the Cloudinary Upload Widget in an Nuxt project.

See other frameworks for examples:

* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/nextjs-upload-widget-signed
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/solid-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/sveltekit-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/vue-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/remix-upload-widget-preset

**Comment by AvaterClasher** [comment]
Assign me this one too.

**Comment by colbyfayock** [comment]
sure its yours!

**Comment by akmittal** [comment]
Hi I have created a PR which resolves this issue https://github.com/cloudinary-community/cloudinary-examples/pull/115
