### ISSUE TITLE
[Example] Astro Product Gallery

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#51]
Create a new example showing how to set up the Cloudinary Product Gallery in an Astro project.

See other frameworks for examples:
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-product-gallery

**Comment by geekysrm** [comment]
Hi @colbyfayock , I have also raised a PR for this issue. https://github.com/cloudinary-community/cloudinary-examples/pull/57
