### ISSUE TITLE
[Example] Svelte Product Gallery

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#54]
Create a new example showing how to set up the Cloudinary Product Gallery in an Svelte project.

See other frameworks for examples:
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-product-gallery

**Comment by geekysrm** [comment]
Hey @colbyfayock , can you give the hacktoberfest tag to this issue?
Also please assign me this issue.

**Comment by colbyfayock** [comment]
@geekysrm ive just added it to the entire repo! so you should be good to go

**Comment by geekysrm** [comment]
@colbyfayock , raised a PR for the above! 
Kindly take a look: https://github.com/cloudinary-community/cloudinary-examples/pull/55
