### ISSUE TITLE
.NET Examples

### ISSUE THREAD

**Issue by adityaoberai** [cloudinary-community/cloudinary-examples#62]
I would love to work on some samples using the .NET SDK, if that's alright?

**Comment by colbyfayock** [comment]
also feel free to update this specific issue for a specific example and tht way if youd like to do another, you can do it as part of a different issue. a few ideas, Upload Widget (clientside), Product Gallery (clientside), uploading serverside (SDK, form, etc), displaying images/videos. i'll let you choose what example youd like to add for this one

**Comment by adityaoberai** [comment]
No worries at all. I'll make sure to have well structured setup steps to help.

Will follow suit from the Node examples

**Comment by adityaoberai** [comment]
@colbyfayock I've added server-side examples for uploading images and videos to start off

**Comment by colbyfayock** [comment]
this was my first time ever running .NET and it worked perfectly! (even had to install the SDK 😂 )

**Comment by adityaoberai** [comment]
> this was my first time ever running .NET and it worked perfectly! (even had to install the SDK 😂 )

That's awesome! 😁  
Btw, I'm working on samples for image transformations as well. Will make a PR for that soon
