### ISSUE TITLE
[Example] PHP - Script for uploading images 

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#66]
Create an example that shows how to upload images using the Cloudinary PHP SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the PHP SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

**Comment by s-vamshi** [comment]
@colbyfayock would like to work on this issue

**Comment by colbyfayock** [comment]
hey @s-vamshi as mentioned on the other Issue, ocne we complete that one I'd be happy to assign this one to you as long as no one else requests it first in the spirit of making sure everyone has an opportunity to contribute 😁 

once the other one is merged, feel free to pick this up if it's available!

**Comment by colbyfayock** [comment]
yup @syedtalaljilani it's all yours!

**Comment by syedtalaljilani** [comment]
> yup @syedtalaljilani it's all yours!

Ok i start working on this

**Comment by syedtalaljilani** [comment]
I create a script which is running fine on localhost using xampp. but this script is not working on terminal due to ssl issue in localhost because localhost is not secure connection.  @colbyfayock  can I push this script?

**Comment by colbyfayock** [comment]
@syedtalaljilani you can try creating a pull request and we can look at it together!

**Comment by syedtalaljilani** [comment]
Ok sure

**Comment by syedtalaljilani** [comment]
@colbyfayock pr is created 🌟
