### ISSUE TITLE
[Example] Go - Uploading images 

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#67]
Create an example that shows how to upload images using the Cloudinary Go SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Go SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

**Comment by colbyfayock** [comment]
sure its all yours @s-vamshi

**Comment by rahul1995** [comment]
Hey can you assign this to me?

**Comment by colbyfayock** [comment]
it looks like @s-vamshi decided not to work on it, so its all yours!

**Comment by rahul1995** [comment]
Created the pull request https://github.com/cloudinary-community/cloudinary-examples/pull/85
