### ISSUE TITLE
[Example] Ruby - Uploading images 

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#68]
Create an example that shows how to upload images using the Cloudinary Ruby SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Ruby SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

**Comment by aazam-gh** [comment]
Hi, I would like to work on this issue :)

**Comment by colbyfayock** [comment]
all yours!
