### ISSUE TITLE
[Example] Dart - Uploading images 

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#69]
Create an example that shows how to upload images using the Cloudinary Dart SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Dart SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

**Comment by adityaoberai** [comment]
I'm new to Dart but happy to help with this

**Comment by colbyfayock** [comment]
that would be great! thank you @adityaoberai, reviewing the other one now 🙌

**Comment by adityaoberai** [comment]
@colbyfayock the PR is ready to review
