### ISSUE TITLE
[Example] Python - Uploading images 

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#70]
Create an example that shows how to upload images using the Cloudinary Python SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Python SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

**Comment by VrajPatelGitHub** [comment]
@colbyfayock i would like to work on this issue please assign this to me.

**Comment by colbyfayock** [comment]
hey @s-vamshi since you were the first one to ask and you completed the other one, i'll go ahed and assign it to you!

@VrajPatelGitHub there are a few other server-side examples of uploading to cloudinary if you'd like to claim one, otherwise if you're interested specifically in Python, I can open up more for Python. what do you think?
