### ISSUE TITLE
[Example] Java - Uploading images 

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#71]
Create an example that shows how to upload images using the Cloudinary Java SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Java SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

**Comment by s-vamshi** [comment]
@colbyfayock would like to work on this issue

**Comment by colbyfayock** [comment]
hey @s-vamshi sure thing! i would recommend however working on one at a time, so i'll first assign you this, and once complete, i can assign you the other one if no one else has asked to claim it before then!

**Comment by s-vamshi** [comment]
Sure @colbyfayock will work on this first.
