### ISSUE TITLE
[Example] Dart - Adding an image as an overlay

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#76]
Add an example as an executable script that adds an image as an overlay to an existing image in Dart.

You can start off by replicating this folder and example from Node:

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-transformations-effects

Particularly the image-overlay.js file, but in Dart.

**Comment by pwk50** [comment]
Hi I'd like to give this issue a try.

**Comment by colbyfayock** [comment]
its all yours!
