### ISSUE TITLE
[Example] Ruby - Adding an image as an overlay

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#77]
Add an example as an executable script that adds an image as an overlay to an existing image in Ruby.

You can start off by replicating this folder and example from Node:

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-transformations-effects

Particularly the image-overlay.js file, but in Ruby.

**Comment by error9098x** [comment]
Is this issue open for hacktoberfest ?

**Comment by error9098x** [comment]
> Add an example as an executable script that adds an image as an overlay to an existing image in Ruby.
> 
> You can start off by replicating this folder and example from Node:
> 
> https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-transformations-effects
> 
> Particularly the image-overlay.js file, but in Ruby.

I would like to give this a try

**Comment by colbyfayock** [comment]
all yours!
