### ISSUE TITLE
[Example] Python - Adding an image as an overlay

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#80]
Add an example as an executable script that adds an image as an overlay to an existing image in Python.

You can start off by replicating this folder and example from Node:

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-transformations-effects

Particularly the image-overlay.js file, but in Python.

**Comment by s-vamshi** [comment]
@colbyfayock can I work on this issue?
Thought of exploring GO lang but didn't have much time so unassigned myself from that issue.

**Comment by colbyfayock** [comment]
all yours @s-vamshi!

**Comment by s-vamshi** [comment]
@colbyfayock 
https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-transformations-effects
In above project, the sample images URL is incomplete or incorrect. Can you confirm ? If its incorrect can you provide the URL ?
